### ISSUE TITLE
None Input Shape

### ISSUE THREAD

**Issue by sofianeMdjk** [thushv89/attention_keras#14]
Hi,
First Thanks a lot for your contribution it's really appreciated. 

I'm training a sequence to sequence model and i would like to have a None parameter in my input_shape and it is currently not possible.
Any possible advice on this issue ?

Thank you.
Best.

**Comment by thushv89** [comment]
Hi @sofianeMdjk ,

You should be able to have a single None parameter in the input shape (for the batch size). I don't think it is possible to have two none parameters in the input. Because there are several reshaping steps involved while computing attention, and to reshape back to the original shape, there should be only one or zero none values in the input shape. 

But if you have seen any solution that allows you to have none parameter in the input shape, please let me know. I'll have a look.

**Comment by sofianeMdjk** [comment]
Thanks for the answer @thushv89 , if i find any suitable solution i'll let you know right away.

**Comment by thushv89** [comment]
Great. I'll close this issue for now. Feel free to open it if needed. :)
